/** @returns an array of `n` elements generated by mapping indices onto elements using `f` (defaults to identity). */
export const arrayOf =
  <T>(n: number, f: (index: number) => T): T[] =>
    Array.from(new Array(n), (_: unknown, i: number) => f(i))

export default arrayOf
